POST http://localhost:3031/api/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "password"
}

###

// REGISTER
POST http://localhost:3031/api/auth/register
Content-Type: application/json

{
  "name": "Test Account2",
  "email": "test2@email.com",
  "password": "password"
}

###


POST http://localhost:3030/api/auth/login-v2
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "password"
}

###


GET http://localhost:3030/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE3MzYwMjUwOTQsImV4cCI6MTczNjExMTQ5NH0.VOiPo9Uo0ABn8p6qXhbAFYaW30W1MoFkwdopadZ1f2w


###

GET http://localhost:3031/api/habit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE3MzYwMjUwOTQsImV4cCI6MTczNjExMTQ5NH0.VOiPo9Uo0ABn8p6qXhbAFYaW30W1MoFkwdopadZ1f2w


###

POST http://localhost:3031/api/habit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE3MzYwMjUwOTQsImV4cCI6MTczNjExMTQ5NH0.VOiPo9Uo0ABn8p6qXhbAFYaW30W1MoFkwdopadZ1f2w

{
  "name": "habit2",
  "description": "habit description2",
  "frequency": 1
}

###
