POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "password"
}

###

POST http://localhost:3030/api/auth/login-v2
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "password"
}

###


GET http://localhost:3030/api/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE3MzU5MTYzNDEsImV4cCI6MTczNjAwMjc0MX0.KsZUF5R7Ja_2U1GHTDywYhfuBUl424vTElxW0WPKKxE


###

GET http://localhost:3030/api/habit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidGVzdEBlbWFpbC5jb20iLCJpYXQiOjE3MzU5MTYzNDEsImV4cCI6MTczNjAwMjc0MX0.KsZUF5R7Ja_2U1GHTDywYhfuBUl424vTElxW0WPKKxE


###

POST http://localhost:3030/api/habit
Content-Type: application/json

{
  "name": "habit one",
  "description": "habit description",
  "frequency": 1
}

###
